### ISSUE TITLE
Leak memory with events

### ISSUE THREAD

**Issue by ithamsteri** [smavros/yaml-to-struct#1]
https://github.com/smavros/yaml-to-struct/blob/9922c0c07a407a36c606dfc1a0fb499f0e1a203c/my_parser.c#L195

Memory Leak. Need free old `event` before get new `event`:
```cpp
if ( !strcmp(buf, cur) ){
    yaml_event_delete(event); /* free old event */
    parse_next(parser,event);
    coil->cur = atoi( (char *) event->data.scalar.value);
} else if ( !strcmp(buf,freq) ){
    yaml_event_delete(event); /* free old event */
    parse_next(parser,event);
    coil->freq = strtod( (char *) event->data.scalar.value, &cb);
}
```
Or delete all call `yaml_event_delete` and modify `parse_next` function:
```cpp
void
parse_next(yaml_parser_t *parser, yaml_event_t *event)
{
    /* parse next scalar. if wrong exit with error */
    yaml_event_delete(event);
    if ( !yaml_parser_parse(parser, event) ){
        printf("Parser error %d\n", parser->error);
        exit(EXIT_FAILURE);
    }
}
```
For empty `event` call `yaml_event_delete` is correct.

**Comment by smavros** [comment]
Nice catch! I had also leaks when I was exiting after an unknown keyword. They are fixed with 668e52c13a8d6196caa82cc921d4c844f59f9a01

Thanks for the feedback.
